// Auto-generated from openrouter_models_non_china_security_filtered.json.
// Regenerate by re-running the extraction script if the catalog needs updating.
import type { CatalogModel } from "./types";

export const MODEL_CATALOG: CatalogModel[] = [
  { id: "cohere/north-mini-code:free", name: "Cohere: North Mini Code (free)", free: true, vision: false, context: 256000, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "google/gemma-4-26b-a4b-it:free", name: "Google: Gemma 4 26B A4B  (free)", free: true, vision: true, context: 262144, score: 25.7, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "google/gemma-4-31b-it:free", name: "Google: Gemma 4 31B (free)", free: true, vision: true, context: 262144, score: 29.4, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "liquid/lfm-2.5-1.2b-instruct:free", name: "LiquidAI: LFM2.5-1.2B-Instruct (free)", free: true, vision: false, context: 32768, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "liquid/lfm-2.5-1.2b-thinking:free", name: "LiquidAI: LFM2.5-1.2B-Thinking (free)", free: true, vision: false, context: 32768, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "meta-llama/llama-3.2-3b-instruct:free", name: "Meta: Llama 3.2 3B Instruct (free)", free: true, vision: false, context: 131072, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "meta-llama/llama-3.3-70b-instruct:free", name: "Meta: Llama 3.3 70B Instruct (free)", free: true, vision: false, context: 131072, score: 9.4, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-3-nano-30b-a3b:free", name: "NVIDIA: Nemotron 3 Nano 30B A3B (free)", free: true, vision: false, context: 256000, score: 14.2, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "NVIDIA: Nemotron 3 Nano Omni (free)", free: true, vision: true, context: 256000, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "NVIDIA: Nemotron 3 Super (free)", free: true, vision: false, context: 1000000, score: 25.4, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-3-ultra-550b-a55b:free", name: "NVIDIA: Nemotron 3 Ultra (free)", free: true, vision: false, context: 1000000, score: 37.8, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-3.5-content-safety:free", name: "NVIDIA: Nemotron 3.5 Content Safety (free)", free: true, vision: true, context: 128000, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-nano-12b-v2-vl:free", name: "NVIDIA: Nemotron Nano 12B 2 VL (free)", free: true, vision: true, context: 128000, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "nvidia/nemotron-nano-9b-v2:free", name: "NVIDIA: Nemotron Nano 9B V2 (free)", free: true, vision: false, context: 128000, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "openai/gpt-oss-120b:free", name: "OpenAI: gpt-oss-120b (free)", free: true, vision: false, context: 131072, score: 23.8, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "openai/gpt-oss-20b:free", name: "OpenAI: gpt-oss-20b (free)", free: true, vision: false, context: 131072, score: 14.9, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "poolside/laguna-m.1:free", name: "Poolside: Laguna M.1 (free)", free: true, vision: false, context: 262144, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "poolside/laguna-xs-2.1:free", name: "Poolside: Laguna XS 2.1 (free)", free: true, vision: false, context: 262144, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "poolside/laguna-xs.2:free", name: "Poolside: Laguna XS.2 (free)", free: true, vision: false, context: 262144, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "ai21/jamba-large-1.7", name: "AI21: Jamba Large 1.7", free: false, vision: false, context: 256000, score: null, promptPricePerM: 2.0, completionPricePerM: 8.0 },
  { id: "allenai/olmo-3-32b-think", name: "AllenAI: Olmo 3 32B Think", free: false, vision: false, context: 65536, score: null, promptPricePerM: 0.15, completionPricePerM: 0.5 },
  { id: "amazon/nova-2-lite-v1", name: "Amazon: Nova 2 Lite", free: false, vision: true, context: 1000000, score: 18.2, promptPricePerM: 0.3, completionPricePerM: 2.5 },
  { id: "amazon/nova-lite-v1", name: "Amazon: Nova Lite 1.0", free: false, vision: true, context: 300000, score: null, promptPricePerM: 0.06, completionPricePerM: 0.24 },
  { id: "amazon/nova-micro-v1", name: "Amazon: Nova Micro 1.0", free: false, vision: false, context: 128000, score: null, promptPricePerM: 0.035, completionPricePerM: 0.14 },
  { id: "amazon/nova-premier-v1", name: "Amazon: Nova Premier 1.0", free: false, vision: true, context: 1000000, score: null, promptPricePerM: 2.5, completionPricePerM: 12.5 },
  { id: "amazon/nova-pro-v1", name: "Amazon: Nova Pro 1.0", free: false, vision: true, context: 300000, score: null, promptPricePerM: 0.8, completionPricePerM: 3.2 },
  { id: "anthropic/claude-3-haiku", name: "Anthropic: Claude 3 Haiku", free: false, vision: true, context: 200000, score: null, promptPricePerM: 0.25, completionPricePerM: 1.25 },
  { id: "anthropic/claude-fable-5", name: "Anthropic: Claude Fable 5", free: false, vision: true, context: 1000000, score: 59.9, promptPricePerM: 10.0, completionPricePerM: 50.0 },
  { id: "anthropic/claude-haiku-4.5", name: "Anthropic: Claude Haiku 4.5", free: false, vision: true, context: 200000, score: 29.6, promptPricePerM: 1.0, completionPricePerM: 5.0 },
  { id: "anthropic/claude-opus-4", name: "Anthropic: Claude Opus 4", free: false, vision: true, context: 200000, score: null, promptPricePerM: 15.0, completionPricePerM: 75.0 },
  { id: "anthropic/claude-opus-4.1", name: "Anthropic: Claude Opus 4.1", free: false, vision: true, context: 200000, score: null, promptPricePerM: 15.0, completionPricePerM: 75.0 },
  { id: "anthropic/claude-opus-4.5", name: "Anthropic: Claude Opus 4.5", free: false, vision: true, context: 200000, score: null, promptPricePerM: 5.0, completionPricePerM: 25.0 },
  { id: "anthropic/claude-opus-4.6", name: "Anthropic: Claude Opus 4.6", free: false, vision: true, context: 1000000, score: null, promptPricePerM: 5.0, completionPricePerM: 25.0 },
  { id: "anthropic/claude-opus-4.7", name: "Anthropic: Claude Opus 4.7", free: false, vision: true, context: 1000000, score: 53.5, promptPricePerM: 5.0, completionPricePerM: 25.0 },
  { id: "anthropic/claude-opus-4.7-fast", name: "Anthropic: Claude Opus 4.7 (Fast)", free: false, vision: true, context: 1000000, score: null, promptPricePerM: 30.0, completionPricePerM: 150.0 },
  { id: "anthropic/claude-opus-4.8", name: "Anthropic: Claude Opus 4.8", free: false, vision: true, context: 1000000, score: 55.7, promptPricePerM: 5.0, completionPricePerM: 25.0 },
  { id: "anthropic/claude-opus-4.8-fast", name: "Anthropic: Claude Opus 4.8 (Fast)", free: false, vision: true, context: 1000000, score: null, promptPricePerM: 10.0, completionPricePerM: 50.0 },
  { id: "anthropic/claude-sonnet-4", name: "Anthropic: Claude Sonnet 4", free: false, vision: true, context: 1000000, score: 28.9, promptPricePerM: 3.0, completionPricePerM: 15.0 },
  { id: "anthropic/claude-sonnet-4.5", name: "Anthropic: Claude Sonnet 4.5", free: false, vision: true, context: 1000000, score: 36.4, promptPricePerM: 3.0, completionPricePerM: 15.0 },
  { id: "anthropic/claude-sonnet-4.6", name: "Anthropic: Claude Sonnet 4.6", free: false, vision: true, context: 1000000, score: 47.2, promptPricePerM: 3.0, completionPricePerM: 15.0 },
  { id: "anthropic/claude-sonnet-5", name: "Anthropic: Claude Sonnet 5", free: false, vision: true, context: 1000000, score: 53.4, promptPricePerM: 2.0, completionPricePerM: 10.0 },
  { id: "cohere/command-a", name: "Cohere: Command A", free: false, vision: false, context: 256000, score: 22.5, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "cohere/command-r-08-2024", name: "Cohere: Command R (08-2024)", free: false, vision: false, context: 128000, score: null, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "cohere/command-r-plus-08-2024", name: "Cohere: Command R+ (08-2024)", free: false, vision: false, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "cohere/command-r7b-12-2024", name: "Cohere: Command R7B (12-2024)", free: false, vision: false, context: 128000, score: null, promptPricePerM: 0.0375, completionPricePerM: 0.15 },
  { id: "google/gemini-2.5-flash", name: "Google: Gemini 2.5 Flash", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.3, completionPricePerM: 2.5 },
  { id: "google/gemini-2.5-flash-lite", name: "Google: Gemini 2.5 Flash Lite", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.1, completionPricePerM: 0.4 },
  { id: "google/gemini-2.5-flash-lite-preview-09-2025", name: "Google: Gemini 2.5 Flash Lite Preview 09-2025", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.1, completionPricePerM: 0.4 },
  { id: "google/gemini-2.5-pro", name: "Google: Gemini 2.5 Pro", free: false, vision: true, context: 1048576, score: 25.8, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "google/gemini-2.5-pro-preview-05-06", name: "Google: Gemini 2.5 Pro Preview 05-06", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "google/gemini-2.5-pro-preview", name: "Google: Gemini 2.5 Pro Preview 06-05", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "google/gemini-3-flash-preview", name: "Google: Gemini 3 Flash Preview", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.5, completionPricePerM: 3.0 },
  { id: "google/gemini-3.1-flash-lite", name: "Google: Gemini 3.1 Flash Lite", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.25, completionPricePerM: 1.5 },
  { id: "google/gemini-3.1-flash-lite-preview", name: "Google: Gemini 3.1 Flash Lite Preview", free: false, vision: true, context: 1048576, score: 25, promptPricePerM: 0.25, completionPricePerM: 1.5 },
  { id: "google/gemini-3.1-pro-preview", name: "Google: Gemini 3.1 Pro Preview", free: false, vision: true, context: 1048576, score: 46.5, promptPricePerM: 2.0, completionPricePerM: 12.0 },
  { id: "google/gemini-3.1-pro-preview-customtools", name: "Google: Gemini 3.1 Pro Preview Custom Tools", free: false, vision: true, context: 1048756, score: null, promptPricePerM: 2.0, completionPricePerM: 12.0 },
  { id: "google/gemini-3.5-flash", name: "Google: Gemini 3.5 Flash", free: false, vision: true, context: 1048576, score: 50.2, promptPricePerM: 1.5, completionPricePerM: 9.0 },
  { id: "google/gemma-2-27b-it", name: "Google: Gemma 2 27B", free: false, vision: false, context: 8192, score: null, promptPricePerM: 0.65, completionPricePerM: 0.65 },
  { id: "google/gemma-3-12b-it", name: "Google: Gemma 3 12B", free: false, vision: true, context: 131072, score: 5.5, promptPricePerM: 0.05, completionPricePerM: 0.15 },
  { id: "google/gemma-3-27b-it", name: "Google: Gemma 3 27B", free: false, vision: true, context: 131072, score: 7.4, promptPricePerM: 0.08, completionPricePerM: 0.16 },
  { id: "google/gemma-3-4b-it", name: "Google: Gemma 3 4B", free: false, vision: true, context: 131072, score: null, promptPricePerM: 0.05, completionPricePerM: 0.1 },
  { id: "google/gemma-3n-e4b-it", name: "Google: Gemma 3n 4B", free: false, vision: false, context: 32768, score: null, promptPricePerM: 0.06, completionPricePerM: 0.12 },
  { id: "google/gemma-4-26b-a4b-it", name: "Google: Gemma 4 26B A4B ", free: false, vision: true, context: 262144, score: 25.7, promptPricePerM: 0.06, completionPricePerM: 0.33 },
  { id: "google/gemma-4-31b-it", name: "Google: Gemma 4 31B", free: false, vision: true, context: 262144, score: 29.4, promptPricePerM: 0.12, completionPricePerM: 0.35 },
  { id: "google/lyria-3-clip-preview", name: "Google: Lyria 3 Clip Preview", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "google/lyria-3-pro-preview", name: "Google: Lyria 3 Pro Preview", free: false, vision: true, context: 1048576, score: null, promptPricePerM: 0.0, completionPricePerM: 0.0 },
  { id: "google/gemini-2.5-flash-image", name: "Google: Nano Banana (Gemini 2.5 Flash Image)", free: false, vision: true, context: 32768, score: null, promptPricePerM: 0.3, completionPricePerM: 2.5 },
  { id: "google/gemini-3.1-flash-image-preview", name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)", free: false, vision: true, context: 131072, score: null, promptPricePerM: 0.5, completionPricePerM: 3.0 },
  { id: "google/gemini-3.1-flash-image", name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image)", free: false, vision: true, context: 131072, score: null, promptPricePerM: 0.5, completionPricePerM: 3.0 },
  { id: "google/gemini-3.1-flash-lite-image", name: "Google: Nano Banana 2 Lite (Gemini 3.1 Flash Lite Image)", free: false, vision: true, context: 65536, score: null, promptPricePerM: 0.25, completionPricePerM: 1.5 },
  { id: "google/gemini-3-pro-image-preview", name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)", free: false, vision: true, context: 65536, score: null, promptPricePerM: 2.0, completionPricePerM: 12.0 },
  { id: "google/gemini-3-pro-image", name: "Google: Nano Banana Pro (Gemini 3 Pro Image)", free: false, vision: true, context: 65536, score: null, promptPricePerM: 2.0, completionPricePerM: 12.0 },
  { id: "ibm-granite/granite-4.0-h-micro", name: "IBM: Granite 4.0 Micro", free: false, vision: false, context: 131000, score: null, promptPricePerM: 0.017, completionPricePerM: 0.112 },
  { id: "ibm-granite/granite-4.1-8b", name: "IBM: Granite 4.1 8B", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.05, completionPricePerM: 0.1 },
  { id: "inflection/inflection-3-productivity", name: "Inflection: Inflection 3 Productivity", free: false, vision: false, context: 8000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "meta-llama/llama-3-8b-instruct", name: "Meta: Llama 3 8B Instruct", free: false, vision: false, context: 8192, score: null, promptPricePerM: 0.14, completionPricePerM: 0.14 },
  { id: "meta-llama/llama-3.1-70b-instruct", name: "Meta: Llama 3.1 70B Instruct", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.4, completionPricePerM: 0.4 },
  { id: "meta-llama/llama-3.1-8b-instruct", name: "Meta: Llama 3.1 8B Instruct", free: false, vision: false, context: 131072, score: 7.6, promptPricePerM: 0.02, completionPricePerM: 0.03 },
  { id: "meta-llama/llama-3.2-11b-vision-instruct", name: "Meta: Llama 3.2 11B Vision Instruct", free: false, vision: true, context: 131072, score: null, promptPricePerM: 0.345, completionPricePerM: 0.345 },
  { id: "meta-llama/llama-3.2-1b-instruct", name: "Meta: Llama 3.2 1B Instruct", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.027, completionPricePerM: 0.201 },
  { id: "meta-llama/llama-3.2-3b-instruct", name: "Meta: Llama 3.2 3B Instruct", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.05, completionPricePerM: 0.33 },
  { id: "meta-llama/llama-3.3-70b-instruct", name: "Meta: Llama 3.3 70B Instruct", free: false, vision: false, context: 131072, score: 9.4, promptPricePerM: 0.1, completionPricePerM: 0.32 },
  { id: "meta-llama/llama-4-maverick", name: "Meta: Llama 4 Maverick", free: false, vision: true, context: 1048576, score: 14.3, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "meta-llama/llama-4-scout", name: "Meta: Llama 4 Scout", free: false, vision: true, context: 10000000, score: 10, promptPricePerM: 0.1, completionPricePerM: 0.3 },
  { id: "meta-llama/llama-guard-4-12b", name: "Meta: Llama Guard 4 12B", free: false, vision: true, context: 163840, score: null, promptPricePerM: 0.18, completionPricePerM: 0.18 },
  { id: "microsoft/phi-4", name: "Microsoft: Phi 4", free: false, vision: false, context: 16384, score: null, promptPricePerM: 0.07, completionPricePerM: 0.14 },
  { id: "mistralai/mistral-large", name: "Mistral Large", free: false, vision: false, context: 128000, score: null, promptPricePerM: 2.0, completionPricePerM: 6.0 },
  { id: "mistralai/mistral-large-2407", name: "Mistral Large 2407", free: false, vision: false, context: 131072, score: null, promptPricePerM: 2.0, completionPricePerM: 6.0 },
  { id: "mistralai/codestral-2508", name: "Mistral: Codestral 2508", free: false, vision: false, context: 256000, score: null, promptPricePerM: 0.3, completionPricePerM: 0.9 },
  { id: "mistralai/devstral-2512", name: "Mistral: Devstral 2 2512", free: false, vision: false, context: 262144, score: 19.2, promptPricePerM: 0.4, completionPricePerM: 2.0 },
  { id: "mistralai/ministral-14b-2512", name: "Mistral: Ministral 3 14B 2512", free: false, vision: true, context: 262144, score: 11.1, promptPricePerM: 0.2, completionPricePerM: 0.2 },
  { id: "mistralai/ministral-3b-2512", name: "Mistral: Ministral 3 3B 2512", free: false, vision: true, context: 131072, score: 6.8, promptPricePerM: 0.1, completionPricePerM: 0.1 },
  { id: "mistralai/ministral-8b-2512", name: "Mistral: Ministral 3 8B 2512", free: false, vision: true, context: 262144, score: 9, promptPricePerM: 0.15, completionPricePerM: 0.15 },
  { id: "mistralai/mistral-large-2512", name: "Mistral: Mistral Large 3 2512", free: false, vision: true, context: 262144, score: 15.9, promptPricePerM: 0.5, completionPricePerM: 1.5 },
  { id: "mistralai/mistral-medium-3", name: "Mistral: Mistral Medium 3", free: false, vision: true, context: 131072, score: null, promptPricePerM: 0.4, completionPricePerM: 2.0 },
  { id: "mistralai/mistral-medium-3.1", name: "Mistral: Mistral Medium 3.1", free: false, vision: true, context: 131072, score: 14.7, promptPricePerM: 0.4, completionPricePerM: 2.0 },
  { id: "mistralai/mistral-medium-3-5", name: "Mistral: Mistral Medium 3.5", free: false, vision: true, context: 262144, score: 29.9, promptPricePerM: 1.5, completionPricePerM: 7.5 },
  { id: "mistralai/mistral-nemo", name: "Mistral: Mistral Nemo", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.02, completionPricePerM: 0.03 },
  { id: "mistralai/mistral-small-24b-instruct-2501", name: "Mistral: Mistral Small 3", free: false, vision: false, context: 32768, score: null, promptPricePerM: 0.05, completionPricePerM: 0.08 },
  { id: "mistralai/mistral-small-3.1-24b-instruct", name: "Mistral: Mistral Small 3.1 24B", free: false, vision: true, context: 128000, score: null, promptPricePerM: 0.351, completionPricePerM: 0.555 },
  { id: "mistralai/mistral-small-3.2-24b-instruct", name: "Mistral: Mistral Small 3.2 24B", free: false, vision: true, context: 128000, score: null, promptPricePerM: 0.075, completionPricePerM: 0.2 },
  { id: "mistralai/mistral-small-2603", name: "Mistral: Mistral Small 4", free: false, vision: true, context: 262144, score: 19.6, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "mistralai/mixtral-8x22b-instruct", name: "Mistral: Mixtral 8x22B Instruct", free: false, vision: false, context: 65536, score: null, promptPricePerM: 2.0, completionPricePerM: 6.0 },
  { id: "mistralai/mistral-saba", name: "Mistral: Saba", free: false, vision: false, context: 32768, score: null, promptPricePerM: 0.2, completionPricePerM: 0.6 },
  { id: "mistralai/voxtral-small-24b-2507", name: "Mistral: Voxtral Small 24B 2507", free: false, vision: false, context: 32000, score: null, promptPricePerM: 0.1, completionPricePerM: 0.3 },
  { id: "morph/morph-v3-fast", name: "Morph: Morph V3 Fast", free: false, vision: false, context: 81920, score: null, promptPricePerM: 0.8, completionPricePerM: 1.2 },
  { id: "morph/morph-v3-large", name: "Morph: Morph V3 Large", free: false, vision: false, context: 262144, score: null, promptPricePerM: 0.9, completionPricePerM: 1.9 },
  { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5", name: "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.4, completionPricePerM: 0.4 },
  { id: "nvidia/nemotron-3-nano-30b-a3b", name: "NVIDIA: Nemotron 3 Nano 30B A3B", free: false, vision: false, context: 262144, score: 14.2, promptPricePerM: 0.05, completionPricePerM: 0.2 },
  { id: "nvidia/nemotron-3-super-120b-a12b", name: "NVIDIA: Nemotron 3 Super", free: false, vision: false, context: 1000000, score: 25.4, promptPricePerM: 0.08, completionPricePerM: 0.45 },
  { id: "nvidia/nemotron-3-ultra-550b-a55b", name: "NVIDIA: Nemotron 3 Ultra", free: false, vision: false, context: 1000000, score: 37.8, promptPricePerM: 0.5, completionPricePerM: 2.2 },
  { id: "openai/gpt-audio", name: "OpenAI: GPT Audio", free: false, vision: false, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "openai/gpt-audio-mini", name: "OpenAI: GPT Audio Mini", free: false, vision: false, context: 128000, score: null, promptPricePerM: 0.6, completionPricePerM: 2.4 },
  { id: "openai/gpt-chat-latest", name: "OpenAI: GPT Chat Latest", free: false, vision: true, context: 400000, score: null, promptPricePerM: 5.0, completionPricePerM: 30.0 },
  { id: "openai/gpt-3.5-turbo", name: "OpenAI: GPT-3.5 Turbo", free: false, vision: false, context: 16385, score: null, promptPricePerM: 0.5, completionPricePerM: 1.5 },
  { id: "openai/gpt-3.5-turbo-0613", name: "OpenAI: GPT-3.5 Turbo (older v0613)", free: false, vision: false, context: 4095, score: null, promptPricePerM: 1.0, completionPricePerM: 2.0 },
  { id: "openai/gpt-3.5-turbo-16k", name: "OpenAI: GPT-3.5 Turbo 16k", free: false, vision: false, context: 16385, score: null, promptPricePerM: 3.0, completionPricePerM: 4.0 },
  { id: "openai/gpt-3.5-turbo-instruct", name: "OpenAI: GPT-3.5 Turbo Instruct", free: false, vision: false, context: 4095, score: null, promptPricePerM: 1.5, completionPricePerM: 2.0 },
  { id: "openai/gpt-4", name: "OpenAI: GPT-4", free: false, vision: false, context: 8191, score: null, promptPricePerM: 30.0, completionPricePerM: 60.0 },
  { id: "openai/gpt-4-turbo", name: "OpenAI: GPT-4 Turbo", free: false, vision: true, context: 128000, score: null, promptPricePerM: 10.0, completionPricePerM: 30.0 },
  { id: "openai/gpt-4-turbo-preview", name: "OpenAI: GPT-4 Turbo Preview", free: false, vision: false, context: 128000, score: null, promptPricePerM: 10.0, completionPricePerM: 30.0 },
  { id: "openai/gpt-4.1", name: "OpenAI: GPT-4.1", free: false, vision: true, context: 1047576, score: null, promptPricePerM: 2.0, completionPricePerM: 8.0 },
  { id: "openai/gpt-4.1-mini", name: "OpenAI: GPT-4.1 Mini", free: false, vision: true, context: 1047576, score: 14.8, promptPricePerM: 0.4, completionPricePerM: 1.6 },
  { id: "openai/gpt-4.1-nano", name: "OpenAI: GPT-4.1 Nano", free: false, vision: true, context: 1047576, score: 9.6, promptPricePerM: 0.1, completionPricePerM: 0.4 },
  { id: "openai/gpt-4o", name: "OpenAI: GPT-4o", free: false, vision: true, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "openai/gpt-4o-2024-05-13", name: "OpenAI: GPT-4o (2024-05-13)", free: false, vision: true, context: 128000, score: null, promptPricePerM: 5.0, completionPricePerM: 15.0 },
  { id: "openai/gpt-4o-2024-08-06", name: "OpenAI: GPT-4o (2024-08-06)", free: false, vision: true, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "openai/gpt-4o-2024-11-20", name: "OpenAI: GPT-4o (2024-11-20)", free: false, vision: true, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "openai/gpt-4o-search-preview", name: "OpenAI: GPT-4o Search Preview", free: false, vision: false, context: 128000, score: null, promptPricePerM: 2.5, completionPricePerM: 10.0 },
  { id: "openai/gpt-4o-mini", name: "OpenAI: GPT-4o-mini", free: false, vision: true, context: 128000, score: null, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "openai/gpt-4o-mini-2024-07-18", name: "OpenAI: GPT-4o-mini (2024-07-18)", free: false, vision: true, context: 128000, score: null, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "openai/gpt-4o-mini-search-preview", name: "OpenAI: GPT-4o-mini Search Preview", free: false, vision: false, context: 128000, score: null, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "openai/gpt-5", name: "OpenAI: GPT-5", free: false, vision: true, context: 400000, score: 34.7, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5-chat", name: "OpenAI: GPT-5 Chat", free: false, vision: true, context: 128000, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5-codex", name: "OpenAI: GPT-5 Codex", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5-image", name: "OpenAI: GPT-5 Image", free: false, vision: true, context: 400000, score: null, promptPricePerM: 10.0, completionPricePerM: 10.0 },
  { id: "openai/gpt-5-image-mini", name: "OpenAI: GPT-5 Image Mini", free: false, vision: true, context: 400000, score: null, promptPricePerM: 2.5, completionPricePerM: 2.0 },
  { id: "openai/gpt-5-mini", name: "OpenAI: GPT-5 Mini", free: false, vision: true, context: 400000, score: 25.3, promptPricePerM: 0.25, completionPricePerM: 2.0 },
  { id: "openai/gpt-5-nano", name: "OpenAI: GPT-5 Nano", free: false, vision: true, context: 400000, score: null, promptPricePerM: 0.05, completionPricePerM: 0.4 },
  { id: "openai/gpt-5-pro", name: "OpenAI: GPT-5 Pro", free: false, vision: true, context: 400000, score: null, promptPricePerM: 15.0, completionPricePerM: 120.0 },
  { id: "openai/gpt-5.1", name: "OpenAI: GPT-5.1", free: false, vision: true, context: 400000, score: 36.9, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5.1-chat", name: "OpenAI: GPT-5.1 Chat", free: false, vision: true, context: 128000, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5.1-codex", name: "OpenAI: GPT-5.1-Codex", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5.1-codex-max", name: "OpenAI: GPT-5.1-Codex-Max", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.25, completionPricePerM: 10.0 },
  { id: "openai/gpt-5.1-codex-mini", name: "OpenAI: GPT-5.1-Codex-Mini", free: false, vision: true, context: 400000, score: null, promptPricePerM: 0.25, completionPricePerM: 2.0 },
  { id: "openai/gpt-5.2", name: "OpenAI: GPT-5.2", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.75, completionPricePerM: 14.0 },
  { id: "openai/gpt-5.2-chat", name: "OpenAI: GPT-5.2 Chat", free: false, vision: true, context: 128000, score: null, promptPricePerM: 1.75, completionPricePerM: 14.0 },
  { id: "openai/gpt-5.2-pro", name: "OpenAI: GPT-5.2 Pro", free: false, vision: true, context: 400000, score: null, promptPricePerM: 21.0, completionPricePerM: 168.0 },
  { id: "openai/gpt-5.2-codex", name: "OpenAI: GPT-5.2-Codex", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.75, completionPricePerM: 14.0 },
  { id: "openai/gpt-5.3-chat", name: "OpenAI: GPT-5.3 Chat", free: false, vision: true, context: 128000, score: null, promptPricePerM: 1.75, completionPricePerM: 14.0 },
  { id: "openai/gpt-5.3-codex", name: "OpenAI: GPT-5.3-Codex", free: false, vision: true, context: 400000, score: null, promptPricePerM: 1.75, completionPricePerM: 14.0 },
  { id: "openai/gpt-5.4", name: "OpenAI: GPT-5.4", free: false, vision: true, context: 1050000, score: 51.4, promptPricePerM: 2.5, completionPricePerM: 15.0 },
  { id: "openai/gpt-5.4-image-2", name: "OpenAI: GPT-5.4 Image 2", free: false, vision: true, context: 272000, score: null, promptPricePerM: 8.0, completionPricePerM: 15.0 },
  { id: "openai/gpt-5.4-mini", name: "OpenAI: GPT-5.4 Mini", free: false, vision: true, context: 400000, score: 40, promptPricePerM: 0.75, completionPricePerM: 4.5 },
  { id: "openai/gpt-5.4-nano", name: "OpenAI: GPT-5.4 Nano", free: false, vision: true, context: 400000, score: 38.2, promptPricePerM: 0.2, completionPricePerM: 1.25 },
  { id: "openai/gpt-5.4-pro", name: "OpenAI: GPT-5.4 Pro", free: false, vision: true, context: 1050000, score: null, promptPricePerM: 30.0, completionPricePerM: 180.0 },
  { id: "openai/gpt-5.5", name: "OpenAI: GPT-5.5", free: false, vision: true, context: 1050000, score: 54.8, promptPricePerM: 5.0, completionPricePerM: 30.0 },
  { id: "openai/gpt-5.5-pro", name: "OpenAI: GPT-5.5 Pro", free: false, vision: true, context: 1050000, score: null, promptPricePerM: 30.0, completionPricePerM: 180.0 },
  { id: "openai/gpt-oss-120b", name: "OpenAI: gpt-oss-120b", free: false, vision: false, context: 131072, score: 23.8, promptPricePerM: 0.03, completionPricePerM: 0.15 },
  { id: "openai/gpt-oss-20b", name: "OpenAI: gpt-oss-20b", free: false, vision: false, context: 131072, score: 14.9, promptPricePerM: 0.029, completionPricePerM: 0.14 },
  { id: "openai/gpt-oss-safeguard-20b", name: "OpenAI: gpt-oss-safeguard-20b", free: false, vision: false, context: 131072, score: null, promptPricePerM: 0.075, completionPricePerM: 0.3 },
  { id: "openai/o1", name: "OpenAI: o1", free: false, vision: true, context: 200000, score: null, promptPricePerM: 15.0, completionPricePerM: 60.0 },
  { id: "openai/o1-pro", name: "OpenAI: o1-pro", free: false, vision: true, context: 200000, score: null, promptPricePerM: 150.0, completionPricePerM: 600.0 },
  { id: "openai/o3", name: "OpenAI: o3", free: false, vision: true, context: 200000, score: null, promptPricePerM: 2.0, completionPricePerM: 8.0 },
  { id: "openai/o3-deep-research", name: "OpenAI: o3 Deep Research", free: false, vision: true, context: 200000, score: null, promptPricePerM: 10.0, completionPricePerM: 40.0 },
  { id: "openai/o3-mini", name: "OpenAI: o3 Mini", free: false, vision: false, context: 200000, score: null, promptPricePerM: 1.1, completionPricePerM: 4.4 },
  { id: "openai/o3-mini-high", name: "OpenAI: o3 Mini High", free: false, vision: false, context: 200000, score: 15.6, promptPricePerM: 1.1, completionPricePerM: 4.4 },
  { id: "openai/o3-pro", name: "OpenAI: o3 Pro", free: false, vision: true, context: 200000, score: null, promptPricePerM: 20.0, completionPricePerM: 80.0 },
  { id: "openai/o4-mini", name: "OpenAI: o4 Mini", free: false, vision: true, context: 200000, score: null, promptPricePerM: 1.1, completionPricePerM: 4.4 },
  { id: "openai/o4-mini-deep-research", name: "OpenAI: o4 Mini Deep Research", free: false, vision: true, context: 200000, score: null, promptPricePerM: 2.0, completionPricePerM: 8.0 },
  { id: "openai/o4-mini-high", name: "OpenAI: o4 Mini High", free: false, vision: true, context: 200000, score: null, promptPricePerM: 1.1, completionPricePerM: 4.4 },
  { id: "poolside/laguna-m.1", name: "Poolside: Laguna M.1", free: false, vision: false, context: 262144, score: null, promptPricePerM: 0.2, completionPricePerM: 0.4 },
  { id: "poolside/laguna-xs-2.1", name: "Poolside: Laguna XS 2.1", free: false, vision: false, context: 262144, score: null, promptPricePerM: 0.06, completionPricePerM: 0.12 },
  { id: "poolside/laguna-xs.2", name: "Poolside: Laguna XS.2", free: false, vision: false, context: 262144, score: null, promptPricePerM: 0.1, completionPricePerM: 0.2 },
  { id: "rekaai/reka-edge", name: "Reka Edge", free: false, vision: true, context: 16384, score: null, promptPricePerM: 0.1, completionPricePerM: 0.1 },
  { id: "rekaai/reka-flash-3", name: "Reka Flash 3", free: false, vision: false, context: 65536, score: null, promptPricePerM: 0.1, completionPricePerM: 0.2 },
  { id: "relace/relace-apply-3", name: "Relace: Relace Apply 3", free: false, vision: false, context: 256000, score: null, promptPricePerM: 0.85, completionPricePerM: 1.25 },
  { id: "relace/relace-search", name: "Relace: Relace Search", free: false, vision: false, context: 256000, score: null, promptPricePerM: 1.0, completionPricePerM: 3.0 },
  { id: "sakana/fugu-ultra", name: "Sakana: Fugu Ultra", free: false, vision: true, context: 1000000, score: null, promptPricePerM: 5.0, completionPricePerM: 30.0 },
  { id: "upstage/solar-pro-3", name: "Upstage: Solar Pro 3", free: false, vision: false, context: 128000, score: 14.1, promptPricePerM: 0.15, completionPricePerM: 0.6 },
  { id: "microsoft/wizardlm-2-8x22b", name: "WizardLM-2 8x22B", free: false, vision: false, context: 65536, score: null, promptPricePerM: 0.62, completionPricePerM: 0.62 },
  { id: "writer/palmyra-x5", name: "Writer: Palmyra X5", free: false, vision: false, context: 1040000, score: null, promptPricePerM: 0.6, completionPricePerM: 6.0 },
  { id: "x-ai/grok-4.20", name: "xAI: Grok 4.20", free: false, vision: true, context: 2000000, score: null, promptPricePerM: 1.25, completionPricePerM: 2.5 },
  { id: "x-ai/grok-4.20-multi-agent", name: "xAI: Grok 4.20 Multi-Agent", free: false, vision: true, context: 2000000, score: null, promptPricePerM: 1.25, completionPricePerM: 2.5 },
  { id: "x-ai/grok-4.3", name: "xAI: Grok 4.3", free: false, vision: true, context: 1000000, score: 37.6, promptPricePerM: 1.25, completionPricePerM: 2.5 },
  { id: "x-ai/grok-4.5", name: "xAI: Grok 4.5", free: false, vision: true, context: 500000, score: 53.8, promptPricePerM: 2.0, completionPricePerM: 6.0 },
  { id: "x-ai/grok-build-0.1", name: "xAI: Grok Build 0.1", free: false, vision: true, context: 256000, score: 39.8, promptPricePerM: 1.0, completionPricePerM: 2.0 },
];
