/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 546838c014eca1f0f113dc861b4923e3)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NODE_ENV: "production";
	SITE_URL: "https://yejunlee.com/chatbot";
	SITE_NAME: "Yejun's Private Chat";
	ENABLE_FILE_HISTORY_BACKUP: "false";
	OPENROUTER_API_KEY: string;
	CHATBOT_USERNAME: string;
	CHATBOT_PASSWORD: string;
	CHATBOT_SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NODE_ENV" | "SITE_URL" | "SITE_NAME" | "ENABLE_FILE_HISTORY_BACKUP" | "OPENROUTER_API_KEY" | "CHATBOT_USERNAME" | "CHATBOT_PASSWORD" | "CHATBOT_SESSION_SECRET">> {}
}
