/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false` (hash: 1184e422f01c444fd1399a2a0b917e2a)
interface __BaseEnv_Env {
	ORIGIN_HOST: "replace-with-your-vercel-project.vercel.app";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ORIGIN_HOST">> {}
}
